name: "✨ Feature Request"
description: Suggest a new idea
title: "[Feature] <short description>"
labels: [enhancement]

body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What feature would you like to see?
      placeholder: "I’d like a way to..."
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why
      description: Why is this feature important?
      placeholder: "This helps because..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered other solutions?

  - type: dropdown
    id: size
    attributes:
      label: Size
      description: Effort estimate
      options:
        - XS
        - S
        - M
        - L
        - XL
    validations:
      required: true

  - type: dropdown
    id: project
    attributes:
      label: Project
      description: Which project does this belong to?
      options:
        - Student Solver Tool
        - Paper
    validations:
      required: true

  - type: input
    id: iteration
    attributes:
      label: Iteration
      description: Weekly iteration (e.g., Week 42)
      placeholder: "Week X"
    validations:
      required: true
