name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      # FOR LATER
      # will need to add actual env vars when
      # DATABASE_URL: "file:./dev.db"
      SKIP_ENV_VALIDATION: true
      CI: true
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      # - name: Generate Prisma Client
      #   run: npm run postinstall

      - name: Lint check
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Type check
        run: npm run typecheck

      - name: Unit tests
        run: npm run test:ci

      - name: Build (ensures prod build is healthy)
        run: npm run build
